### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by EchterAgo** [honest-cash/simple-bitcoin-wallet#1]
I get "ReferenceError: window is not defined" when trying to use this in node.js.
`var simpleBitcoinWallet = require("simple-bitcoin-wallet")`

https://npm.runkit.com/simple-bitcoin-wallet
RunKit suggests this:

> Fix: Use global instead of window.
> RunKit is a node environment, so window and other browser features won’t exist. If you’re just trying to access the global object, you can simply use global instead.

**Comment by adrianbarwicki** [comment]
Hey, you can build own version for `node` target. Check out these two uncommented lines:
https://github.com/honest-cash/simple-bitcoin-wallet/blob/master/webpack.config.js#L8

As we are using simple-bitcoin-wallet only in the front-end, so the default build artifact is for the browsers.

**Comment by EchterAgo** [comment]
Ah, good to know, thanks. I'm quite inexperienced with JavaScript, so maybe this is something that people should already know, so I'll close this.
